name: camp_final
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  flutter_triple: ^1.2.7+2
  dio: ^4.0.4
  dartz: ^0.10.1
  google_fonts: ^2.3.1
  flutter_native_splash: ^2.0.4
  flutter_switch: ^0.3.2
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^1.0.0
  triple_test: ^1.0.0
  modular_test: ^1.0.1+1


flutter:
  
  
  uses-material-design: true

  assets:
  - assets/images/

  